# Generated by Django 4.2.4 on 2023-08-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('index', models.CharField(blank=True, max_length=50, null=True, verbose_name='Индекс')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('delivery', models.CharField(max_length=150, verbose_name='Способ доставки')),
                ('payment', models.CharField(max_length=150, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='orders.orders', verbose_name='Заказ')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
