# Generated by Django 4.2.4 on 2023-08-28 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.supplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
