# Generated by Django 4.2.4 on 2023-08-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_sup',
            field=models.CharField(max_length=100, verbose_name='Артикул_поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Ссылка на продукт'),
        ),
    ]
