# Generated by Django 4.2.4 on 2023-08-31 19:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_article_sup_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='images/', verbose_name='Картинка'),
        ),
    ]
