# Generated by Django 4.2.4 on 2023-09-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_temporarilylinksbrrc_options_and_more'),
        ('products', '0004_alter_productimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='categories.subcategory', verbose_name='Категория'),
        ),
    ]
