# Generated by Django 4.2.4 on 2023-09-01 23:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 1200], upload_to='images/', verbose_name='Картинка'),
        ),
    ]
