# Generated by Django 4.2.4 on 2023-09-01 23:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPG', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='images/', verbose_name='Картинка'),
        ),
    ]
