# Generated by Django 4.2.4 on 2023-09-05 19:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='img',
        ),
        migrations.AddField(
            model_name='productimage',
            name='img_high',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[720, 540], upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='img_low',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[180, 120], upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='img_medium',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[500, 330], upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
