# Generated by Django 4.2.4 on 2023-09-12 00:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productimage_img_productimage_img_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img_high',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=100, scale=None, size=[720, 540], upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_low',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=100, scale=None, size=[180, 120], upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_medium',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=100, scale=None, size=[500, 330], upload_to='images/', verbose_name='Картинка'),
        ),
    ]
