# Generated by Django 4.2.4 on 2023-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarilyLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Промежуточная ссылка',
            },
        ),
    ]
