# Generated by Django 4.2.4 on 2023-08-28 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_temporarilylinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarilyLinksBRRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Промежуточная ссылки',
            },
        ),
        migrations.DeleteModel(
            name='TemporarilyLinks',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='temporarilylinksbrrc',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
