# Generated by Django 4.2.4 on 2023-08-28 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_temporarilylinksbrrc_delete_temporarilylinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarilylinksbrrc',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='День временных ссылок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='brrc_link',
            field=models.TextField(verbose_name='Ссылка на парсинг brrc'),
        ),
    ]
