# Generated by Django 4.2.4 on 2023-08-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_subcategory_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='category',
        ),
    ]
