# Generated by Django 4.2.4 on 2023-08-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_rename_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarilylinksbrrc',
            options={'verbose_name': 'Ссылка BRRC', 'verbose_name_plural': 'Промежуточная ссылки BRRC'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='fasrshop_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг fasrshop'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='brrc_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг brrc'),
        ),
        migrations.CreateModel(
            name='TemporarilyLinksFasrshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='День временных ссылок')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Ссылка Fasrshop',
                'verbose_name_plural': 'Промежуточная ссылки Fasrshop',
            },
        ),
    ]
