# Generated by Django 4.2.4 on 2023-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_subcategory_rcstore_link_temporarilylinksrcstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='hobbycenter_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг hobbycenter'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rcstore_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг rcstore'),
        ),
    ]
