# Generated by Django 4.2.4 on 2023-10-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_subcategory_shopntoys_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='micromachine_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг micromachine'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='snt_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг snt'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ultrarobox_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг ultrarobox'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='shopntoys_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на парсинг shopntoys'),
        ),
        migrations.CreateModel(
            name='TemporarilyLinksUlrarobox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='День временных ссылок')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Ссылка Ulrarobox',
                'verbose_name_plural': 'Промежуточные ссылки Ulrarobox',
            },
        ),
        migrations.CreateModel(
            name='TemporarilyLinksSnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='День временных ссылок')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Ссылка Snt',
                'verbose_name_plural': 'Промежуточные ссылки Snt',
            },
        ),
        migrations.CreateModel(
            name='TemporarilyLinksMicromachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(verbose_name='Промежуточные ссылки на парсинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='День временных ссылок')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Ссылка Micromachine',
                'verbose_name_plural': 'Промежуточные ссылки Micromachine',
            },
        ),
    ]
