# Generated by Django 4.2.4 on 2023-10-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_subcategory_micromachine_link_subcategory_snt_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporarilyLinksUlrarobox',
            new_name='TemporarilyLinksUltrarobox',
        ),
    ]
